{% set version = "2020f" %}

package:
  name: tzcode
  version: {{ version }}

source:
  url: https://data.iana.org/time-zones/releases/tzdb-{{ version }}.tar.lz
  sha256: 6226b38b7434b66f2c5b730642c67b6b7cd42c035b8442e63e5b8cb5261ddfc5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - lzip
    - make
  host:
  run:

test:
  commands:
    - tzselect --help
    - zdump --help
    - zic --help

about:
  home: https://www.iana.org/time-zones
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Time Zone Database (often called tz or zoneinfo)
  description: |
    The Time Zone Database (often called tz or zoneinfo) contains
    code and data that represent the history of local time for many
    representative locations around the globe. It is updated periodically
    to reflect changes made by political bodies to time zone boundaries,
    UTC offsets, and daylight-saving rules. 
  doc_url: https://tools.ietf.org/html/rfc6557

extra:
  recipe-maintainers:
    - sodre
    - ocefpaf
